ARG version

FROM ubuntu:${version}

RUN apt update \
 && DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends \
        ca-certificates \
        python3-apt \
        python3-dev \
        python3-minimal \
        sudo \
 && apt clean \
 && rm -rf /var/lib/apt/lists/*

ADD docker-entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT [ "/usr/local/bin/entrypoint.sh" ]
