ARG version

FROM ubuntu:${version}

RUN apt update \
 && DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends \
        ca-certificates \
        python3-apt \
        python3-dev \
        python3-minimal \
        sudo \
 && apt clean \
 && rm -rf /var/lib/apt/lists/*

COPY entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/*

ENTRYPOINT [ "entrypoint.sh" ]
