---
all:
  hosts:
  children:
    prod:
    test:
      hosts:
        local-ubuntu-18-04:
          ansible_become: yes
          ansible_connection: docker
          ansible_host: local-ubuntu-18-04
          ansible_user: root
        local-ubuntu-20-04:
          ansible_become: yes
          ansible_connection: docker
          ansible_host: local-ubuntu-20-04
          ansible_user: root
