---

- hosts: "{{ used_ansible_hosts | default('all') }}"
  become: yes
  tasks:
  - name: Install docker-compose
    get_url:
      url: '{{ binaries_docker_compose_url | join("") }}'
      dest: '{{ binaries_docker_compose_path }}'
      mode: '0755'
    when:
    - binaries_docker_compose_state == 'present'
    - ansible_version.string == used_ansible_version

  - name: Uninstall docker-compose
    file:
      path: '{{ binaries_docker_compose_path }}'
      state: absent
    when:
    - binaries_docker_compose_state == 'absent'
    - ansible_version.string == used_ansible_version
