- hosts: all
  become: yes
  vars:
    bin_dir: /usr/local/bin
  tasks:
  - name: Install bazelisk
    get_url:
      url: 'https://github.com/bazelbuild/bazelisk/releases/download/v{{ values.all.bazelisk_version }}/bazelisk-linux-amd64'
      dest: '{{ bin_dir }}/bazelisk'
      mode: '0755'
    when:
    - ansible_version.string == values.all.ansible_version

  - name: Install docker-compose
    get_url:
      url: 'https://github.com/docker/compose/releases/download/{{ values.all.docker_compose_version }}/docker-compose-Linux-x86_64'
      dest: '{{ bin_dir }}/docker-compose'
      mode: '0755'
    when:
    - ansible_version.string == values.all.ansible_version
