- hosts: all
  become: yes
  tasks:
  - name: Install bazelisk
    get_url:
      url: 'https://github.com/bazelbuild/bazelisk/releases/download/v{{ values.all.bazelisk.version }}/bazelisk-linux-amd64'
      dest: '{{ values.all.bazelisk.path }}'
      mode: '0755'
    when:
    - packages.bazelisk == 'present'
    - ansible_version.string == values.all.ansible_version

  - name: Uninstall bazelisk
    file:
      path: '{{ values.all.bazelisk.path }}'
      state: absent
    when:
    - packages.bazelisk == 'absent'
    - ansible_version.string == values.all.ansible_version

  - name: Install docker-compose
    get_url:
      url: 'https://github.com/docker/compose/releases/download/{{ values.all.docker_compose.version }}/docker-compose-Linux-x86_64'
      dest: '{{ values.all.docker_compose.path }}'
      mode: '0755'
    when:
    - packages.docker_compose == 'present'
    - ansible_version.string == values.all.ansible_version

  - name: Uninstall docker-compose
    file:
      path: '{{ values.all.docker_compose.path }}'
      state: absent
    when:
    - packages.bazelisk == 'absent'
    - ansible_version.string == values.all.ansible_version
