- hosts: all
  become: yes
  tasks:
  - name: Upgrade Debian based hosts
    apt:
      name: '*'
      state: latest
      update_cache: yes
    when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'

  - name: Upgrade RedHat based hosts
    yum:
      name: '*'
      state: latest
    when:
    - ansible_os_family == 'RedHat'
    - ansible_pkg_mgr == 'yum'
