- hosts: all
  become: yes
  tasks:
  - name: Upgrade Debian based hosts
    apt:
      name: '*'
      state: latest
      update_cache: yes
    when:
    - ansible_os_family == 'Debian'
    - ansible_pkg_mgr == 'apt'
    - ansible_version.major is version('2', '==')
    - ansible_version.minor is version('9', '==')

  - name: Upgrade RedHat based hosts
    yum:
      name: '*'
      state: latest
    when:
    - ansible_os_family == 'RedHat'
    - ansible_pkg_mgr == 'yum'
    - ansible_version.major is version('2', '==')
    - ansible_version.minor is version('9', '==')
